export const userConstants = {
    USERS_LIST_REQUEST: 'USERS_LIST_REQUEST',
    USERS_LIST_REQUEST_SUCCESS: 'USERS_LIST_REQUEST_SUCCESS',
    USERS_LIST_REQUEST_FAILURE: 'USERS_LIST_REQUEST_FAILURE',

    SINGLE_USER_DATA_REQUEST: 'SINGLE_USER_DATA_REQUEST',
    SINGLE_USER_DATA_REQUEST_SUCCESS: 'SINGLE_USER_DATA_REQUEST_SUCCESS',
    SINGLE_USER_DATA_REQUEST_FAILURE: 'SINGLE_USER_DATA_REQUEST_FAILURE',

    ADD_USER_REQUEST : 'ADD_USER_REQUEST',
    ADD_USER_REQUEST_SUCCESS : 'ADD_USER_REQUEST_SUCCESS',
    ADD_USER_REQUEST_FAILURE : 'ADD_USER_REQUEST_FAILURE',

    EDIT_USER_REQUEST : 'EDIT_USER_REQUEST',
    EDIT_USER_REQUEST_SUCCESS : 'EDIT_USER_REQUEST_SUCCESS',
    EDIT_USER_REQUEST_FAILURE : 'EDIT_USER_REQUEST_FAILURE',

    DELETE_USER_REQUEST : 'DELETE_USER_REQUEST',
    DELETE_USER_REQUEST_SUCCESS : 'DELETE_USER_REQUEST_SUCCESS',
    DELETE_USER_REQUEST_FAILURE : 'DELETE_USER_REQUEST_FAILURE',
}